[2025-04-04T22:57:14.133+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:57:14.138+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:57:14.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T22:57:14.140+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:14.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:57:14.144+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:14.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:57:14.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:57:14.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T22:57:44.594+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:57:44.600+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:57:44.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T22:57:44.603+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:44.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:57:44.607+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:44.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:57:44.607+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:57:44.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.036 seconds
[2025-04-04T22:58:15.021+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:58:15.027+0000] {processor.py:186} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:58:15.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T22:58:15.029+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:15.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:58:15.033+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:15.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:58:15.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:58:15.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T22:58:45.466+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:58:45.473+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:58:45.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T22:58:45.475+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:45.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:58:45.479+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:45.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:58:45.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:58:45.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T22:59:15.927+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:59:15.933+0000] {processor.py:186} INFO - Started process (PID=281) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:59:15.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T22:59:15.935+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:15.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:59:15.939+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:15.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:59:15.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:59:15.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T22:59:46.297+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:59:46.302+0000] {processor.py:186} INFO - Started process (PID=284) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:59:46.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T22:59:46.304+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:46.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:59:46.308+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:46.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:59:46.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T22:59:46.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:00:16.751+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:00:16.758+0000] {processor.py:186} INFO - Started process (PID=287) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:00:16.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:00:16.760+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:16.760+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:00:16.764+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:16.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:00:16.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:00:16.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:00:47.212+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:00:47.219+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:00:47.219+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:00:47.221+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:47.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:00:47.224+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:47.223+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:00:47.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:00:47.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:01:17.626+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:01:17.630+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:01:17.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:01:17.632+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:17.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:01:17.635+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:17.634+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:01:17.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:01:17.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:01:48.049+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:01:48.056+0000] {processor.py:186} INFO - Started process (PID=296) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:01:48.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:01:48.058+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:48.058+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:01:48.062+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:48.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:01:48.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:01:48.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:02:18.513+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:02:18.519+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:02:18.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:02:18.521+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:18.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:02:18.524+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:18.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:02:18.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:02:18.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:02:48.930+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:02:48.936+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:02:48.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:02:48.938+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:48.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:02:48.942+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:48.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:02:48.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:02:48.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:03:19.417+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:03:19.422+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:03:19.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:03:19.424+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:19.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:03:19.427+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:19.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:03:19.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:03:19.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:03:49.731+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:03:49.737+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:03:49.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:03:49.739+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:49.739+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:03:49.742+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:49.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:03:49.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:03:49.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:04:20.178+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:04:20.184+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:04:20.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:04:20.186+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:20.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:04:20.189+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:20.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:04:20.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:04:20.207+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:04:50.612+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:04:50.618+0000] {processor.py:186} INFO - Started process (PID=314) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:04:50.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:04:50.620+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:50.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:04:50.624+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:50.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:04:50.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:04:50.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:05:20.998+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:05:21.004+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:05:21.005+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:05:21.007+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:21.007+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:05:21.011+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:21.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:05:21.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:05:21.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.036 seconds
[2025-04-04T23:05:51.450+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:05:51.457+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:05:51.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:05:51.459+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:51.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:05:51.462+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:51.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:05:51.463+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:05:51.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:06:21.866+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:06:21.872+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:06:21.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:06:21.874+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:21.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:06:21.878+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:21.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:06:21.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:06:21.898+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:06:52.287+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:06:52.293+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:06:52.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:06:52.295+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:52.295+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:06:52.300+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:52.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:06:52.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:06:52.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:07:22.692+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:07:22.699+0000] {processor.py:186} INFO - Started process (PID=329) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:07:22.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:07:22.701+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:22.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:07:22.704+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:22.703+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:07:22.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:07:22.723+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:07:53.117+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:07:53.123+0000] {processor.py:186} INFO - Started process (PID=332) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:07:53.123+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:07:53.125+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:53.125+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:07:53.128+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:53.127+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:07:53.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:07:53.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:08:23.510+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:08:23.517+0000] {processor.py:186} INFO - Started process (PID=335) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:08:23.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:08:23.519+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:23.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:08:23.523+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:23.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:08:23.523+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:08:23.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:08:53.906+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:08:53.913+0000] {processor.py:186} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:08:53.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:08:53.915+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:53.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:08:53.918+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:53.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:08:53.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:08:53.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:09:24.300+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:09:24.307+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:09:24.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:09:24.308+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:24.308+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:09:24.312+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:24.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:09:24.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:09:24.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:09:54.640+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:09:54.646+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:09:54.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:09:54.648+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:54.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:09:54.652+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:54.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:09:54.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:09:54.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:10:25.028+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:10:25.034+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:10:25.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:10:25.036+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:25.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:10:25.040+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:25.039+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:10:25.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:10:25.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:10:55.418+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:10:55.424+0000] {processor.py:186} INFO - Started process (PID=350) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:10:55.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:10:55.426+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:55.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:10:55.429+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:55.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:10:55.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:10:55.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:11:25.775+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:11:25.781+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:11:25.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:11:25.784+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:25.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:11:25.787+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:25.786+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:11:25.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:11:25.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:11:56.153+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:11:56.159+0000] {processor.py:186} INFO - Started process (PID=356) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:11:56.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:11:56.161+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:56.161+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:11:56.165+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:56.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:11:56.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:11:56.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:12:26.469+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:12:26.476+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:12:26.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:12:26.478+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:26.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:12:26.481+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:26.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:12:26.482+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:12:26.499+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:12:56.804+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:12:56.810+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:12:56.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:12:56.812+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:56.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:12:56.816+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:56.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:12:56.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:12:56.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:13:27.162+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:13:27.168+0000] {processor.py:186} INFO - Started process (PID=365) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:13:27.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:13:27.170+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:27.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:13:27.173+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:27.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:13:27.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:13:27.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:13:57.528+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:13:57.535+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:13:57.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:13:57.537+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:57.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:13:57.541+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:57.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:13:57.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:13:57.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.036 seconds
[2025-04-04T23:14:27.904+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:14:27.909+0000] {processor.py:186} INFO - Started process (PID=371) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:14:27.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:14:27.911+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:27.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:14:27.915+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:27.913+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:14:27.915+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:14:27.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:14:58.263+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:14:58.270+0000] {processor.py:186} INFO - Started process (PID=374) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:14:58.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:14:58.272+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:58.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:14:58.276+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:58.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:14:58.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:14:58.295+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:15:28.573+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:15:28.579+0000] {processor.py:186} INFO - Started process (PID=377) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:15:28.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:15:28.581+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:28.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:15:28.584+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:28.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:15:28.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:15:28.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:15:58.923+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:15:58.929+0000] {processor.py:186} INFO - Started process (PID=380) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:15:58.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:15:58.931+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:58.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:15:58.934+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:58.933+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:15:58.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:15:58.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:16:29.264+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:16:29.269+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:16:29.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:16:29.271+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:29.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:16:29.274+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:29.273+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:16:29.275+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:16:29.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:16:59.636+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:16:59.642+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:16:59.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:16:59.645+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:59.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:16:59.648+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:59.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:16:59.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:16:59.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:17:30.048+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:17:30.054+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:17:30.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:17:30.056+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:17:30.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:17:30.060+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:17:30.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:17:30.060+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:17:30.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:18:00.392+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:18:00.398+0000] {processor.py:186} INFO - Started process (PID=392) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:18:00.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:18:00.400+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:00.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:18:00.403+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:00.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:18:00.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:18:00.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:18:30.729+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:18:30.734+0000] {processor.py:186} INFO - Started process (PID=395) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:18:30.734+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:18:30.735+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:30.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:18:30.739+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:30.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:18:30.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:18:30.754+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.027 seconds
[2025-04-04T23:19:01.070+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:19:01.077+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:19:01.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:19:01.079+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:01.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:19:01.082+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:01.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:19:01.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:19:01.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:19:31.454+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:19:31.460+0000] {processor.py:186} INFO - Started process (PID=401) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:19:31.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:19:31.462+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:31.462+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:19:31.465+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:31.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:19:31.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:19:31.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:20:01.768+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:20:01.774+0000] {processor.py:186} INFO - Started process (PID=404) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:20:01.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:20:01.776+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:01.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:20:01.780+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:01.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:20:01.780+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:20:01.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:20:32.099+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:20:32.104+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:20:32.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:20:32.106+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:32.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:20:32.110+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:32.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:20:32.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:20:32.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:21:02.407+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:21:02.413+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:21:02.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:21:02.415+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:02.415+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:21:02.419+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:02.418+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:21:02.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:21:02.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:21:32.708+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:21:32.713+0000] {processor.py:186} INFO - Started process (PID=413) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:21:32.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:21:32.715+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:32.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:21:32.718+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:32.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:21:32.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:21:32.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:22:03.098+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:22:03.105+0000] {processor.py:186} INFO - Started process (PID=416) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:22:03.105+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:22:03.107+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:03.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:22:03.110+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:03.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:22:03.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:22:03.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:22:33.422+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:22:33.429+0000] {processor.py:186} INFO - Started process (PID=419) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:22:33.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:22:33.431+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:33.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:22:33.435+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:33.434+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:22:33.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:22:33.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:23:03.753+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:23:03.761+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:23:03.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:23:03.763+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:03.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:23:03.766+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:03.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:23:03.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:23:03.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:23:34.101+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:23:34.106+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:23:34.106+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:23:34.108+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:34.108+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:23:34.112+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:34.110+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:23:34.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:23:34.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:24:04.447+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:24:04.453+0000] {processor.py:186} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:24:04.454+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:24:04.455+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:04.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:24:04.458+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:04.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:24:04.459+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:24:04.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:24:34.777+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:24:34.781+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:24:34.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:24:34.783+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:34.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:24:34.786+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:34.785+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:24:34.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:24:34.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.029 seconds
[2025-04-04T23:25:05.034+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:25:05.041+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:25:05.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:25:05.043+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:05.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:25:05.046+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:05.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:25:05.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:25:05.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:25:35.340+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:25:35.345+0000] {processor.py:186} INFO - Started process (PID=437) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:25:35.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:25:35.347+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:35.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:25:35.350+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:35.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:25:35.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:25:35.368+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:26:05.633+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:26:05.639+0000] {processor.py:186} INFO - Started process (PID=440) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:26:05.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:26:05.641+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:05.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:26:05.645+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:05.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:26:05.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:26:05.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:26:35.947+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:26:35.954+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:26:35.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:26:35.956+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:35.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:26:35.959+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:35.958+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:26:35.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:26:35.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:27:06.303+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:27:06.310+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:27:06.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:27:06.312+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:06.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:27:06.315+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:06.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:27:06.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:27:06.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:27:36.546+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:27:36.552+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:27:36.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:27:36.554+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:36.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:27:36.558+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:36.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:27:36.558+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:27:36.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:28:06.835+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:28:06.840+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:28:06.841+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:28:06.843+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:06.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:28:06.846+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:06.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:28:06.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:28:06.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:28:37.183+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:28:37.189+0000] {processor.py:186} INFO - Started process (PID=455) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:28:37.190+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:28:37.191+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:37.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:28:37.195+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:37.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:28:37.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:28:37.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:29:07.486+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:29:07.493+0000] {processor.py:186} INFO - Started process (PID=458) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:29:07.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:29:07.495+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:07.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:29:07.498+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:07.497+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:29:07.499+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:29:07.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:29:37.733+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:29:37.739+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:29:37.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:29:37.742+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:37.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:29:37.745+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:37.744+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:29:37.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:29:37.760+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.029 seconds
[2025-04-04T23:30:07.996+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:30:08.002+0000] {processor.py:186} INFO - Started process (PID=464) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:30:08.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:30:08.004+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:08.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:30:08.007+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:08.006+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:30:08.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:30:08.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.029 seconds
[2025-04-04T23:30:38.288+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:30:38.295+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:30:38.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:30:38.297+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:38.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:30:38.300+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:38.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:30:38.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:30:38.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:31:08.533+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:31:08.540+0000] {processor.py:186} INFO - Started process (PID=470) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:31:08.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:31:08.541+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:08.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:31:08.545+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:08.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:31:08.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:31:08.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:31:38.804+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:31:38.811+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:31:38.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:31:38.813+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:38.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:31:38.816+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:38.815+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:31:38.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:31:38.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:32:09.004+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:32:09.009+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:32:09.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:32:09.011+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:09.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:32:09.014+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:09.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:32:09.015+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:32:09.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.031 seconds
[2025-04-04T23:32:39.289+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:32:39.295+0000] {processor.py:186} INFO - Started process (PID=479) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:32:39.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:32:39.297+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:39.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:32:39.301+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:39.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:32:39.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:32:39.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:33:09.570+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:33:09.576+0000] {processor.py:186} INFO - Started process (PID=482) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:33:09.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:33:09.579+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:33:09.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:33:09.582+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:33:09.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:33:09.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:33:09.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:33:39.849+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:33:39.855+0000] {processor.py:186} INFO - Started process (PID=485) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:33:39.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:33:39.857+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:33:39.857+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:33:39.861+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:33:39.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:33:39.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:33:39.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.030 seconds
[2025-04-04T23:34:10.106+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:34:10.113+0000] {processor.py:186} INFO - Started process (PID=488) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:34:10.113+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:34:10.115+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:10.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:34:10.119+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:10.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:34:10.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:34:10.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.038 seconds
[2025-04-04T23:34:40.252+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:34:40.258+0000] {processor.py:186} INFO - Started process (PID=491) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:34:40.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:34:40.261+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:40.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:34:40.265+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:40.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:34:40.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:34:40.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.035 seconds
[2025-04-04T23:35:10.557+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:35:10.564+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:35:10.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:35:10.565+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:10.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:35:10.569+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:10.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:35:10.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:35:10.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:35:40.860+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:35:40.866+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:35:40.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:35:40.868+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:40.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:35:40.871+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:40.870+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:35:40.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:35:40.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:36:11.091+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:36:11.101+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:36:11.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:36:11.103+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:11.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:36:11.107+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:11.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:36:11.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:36:11.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.040 seconds
[2025-04-04T23:36:41.368+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:36:41.374+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:36:41.374+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:36:41.376+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:41.376+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:36:41.379+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:41.378+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:36:41.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:36:41.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.029 seconds
[2025-04-04T23:37:11.566+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:37:11.573+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:37:11.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:37:11.575+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:11.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:37:11.578+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:11.577+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:37:11.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:37:11.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:37:41.829+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:37:41.836+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:37:41.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:37:41.839+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:41.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:37:41.842+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:41.841+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:37:41.843+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:37:41.863+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.037 seconds
[2025-04-04T23:38:12.105+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:38:12.112+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:38:12.112+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:38:12.114+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:12.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:38:12.118+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:12.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:38:12.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:38:12.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:38:42.285+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:38:42.291+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:38:42.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:38:42.293+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:42.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:38:42.297+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:42.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:38:42.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:38:42.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.034 seconds
[2025-04-04T23:39:12.523+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:39:12.530+0000] {processor.py:186} INFO - Started process (PID=518) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:39:12.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:39:12.532+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:12.532+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:39:12.536+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:12.535+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:39:12.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:39:12.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.037 seconds
[2025-04-04T23:39:43.382+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:39:43.388+0000] {processor.py:186} INFO - Started process (PID=521) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:39:43.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:39:43.390+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:43.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:39:43.393+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:43.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:39:43.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:39:43.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.033 seconds
[2025-04-04T23:40:13.975+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:40:13.982+0000] {processor.py:186} INFO - Started process (PID=524) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:40:13.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:40:13.984+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:13.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:40:13.987+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:13.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:40:13.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:40:14.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
[2025-04-04T23:40:44.150+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:40:44.156+0000] {processor.py:186} INFO - Started process (PID=527) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:40:44.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:40:44.158+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:44.158+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:40:44.162+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:44.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:40:44.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:40:44.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.036 seconds
[2025-04-04T23:41:14.402+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:41:14.410+0000] {processor.py:186} INFO - Started process (PID=530) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:41:14.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:41:14.412+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:14.412+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:41:14.416+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:14.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:41:14.417+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:41:14.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.036 seconds
[2025-04-04T23:41:44.578+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:41:44.583+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:41:44.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_model_retrain.py for tasks to queue
[2025-04-04T23:41:44.585+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:44.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:41:44.589+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:44.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_model_retrain.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_model_retrain.py", line 6, in <module>
    from include.ml_utils import clean_data_polars, transform_features_polars
  File "/opt/airflow/dags/include/ml_utils.py", line 1, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:41:44.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_model_retrain.py
[2025-04-04T23:41:44.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_model_retrain.py took 0.032 seconds
