[2025-04-04T22:57:03.856+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:57:03.861+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:57:03.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T22:57:03.863+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:03.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:57:03.866+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:03.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:57:03.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:57:03.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.030 seconds
[2025-04-04T22:57:34.313+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:57:34.320+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:57:34.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T22:57:34.323+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:34.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:57:34.326+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:57:34.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:57:34.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:57:34.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T22:58:04.924+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:58:04.930+0000] {processor.py:186} INFO - Started process (PID=274) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:58:04.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T22:58:04.933+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:04.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:58:04.935+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:04.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:58:04.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:58:04.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T22:58:35.380+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:58:35.387+0000] {processor.py:186} INFO - Started process (PID=277) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:58:35.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T22:58:35.390+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:35.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:58:35.392+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:58:35.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:58:35.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:58:35.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T22:59:05.833+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:59:05.840+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:59:05.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T22:59:05.843+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:05.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:59:05.846+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:05.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:59:05.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:59:05.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T22:59:36.226+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T22:59:36.233+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:59:36.233+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T22:59:36.236+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:36.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:59:36.239+0000] {logging_mixin.py:190} INFO - [2025-04-04T22:59:36.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T22:59:36.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T22:59:36.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:00:06.671+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:00:06.676+0000] {processor.py:186} INFO - Started process (PID=286) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:00:06.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:00:06.679+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:06.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:00:06.681+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:06.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:00:06.682+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:00:06.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:00:37.107+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:00:37.114+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:00:37.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:00:37.116+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:37.116+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:00:37.119+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:00:37.118+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:00:37.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:00:37.136+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:01:07.533+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:01:07.539+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:01:07.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:01:07.542+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:07.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:01:07.545+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:07.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:01:07.545+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:01:07.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:01:37.970+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:01:37.976+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:01:37.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:01:37.978+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:37.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:01:37.981+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:01:37.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:01:37.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:01:37.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:02:08.417+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:02:08.423+0000] {processor.py:186} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:02:08.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:02:08.425+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:08.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:02:08.427+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:08.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:02:08.428+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:02:08.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:02:38.845+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:02:38.851+0000] {processor.py:186} INFO - Started process (PID=301) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:02:38.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:02:38.853+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:38.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:02:38.856+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:02:38.855+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:02:38.856+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:02:38.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.028 seconds
[2025-04-04T23:03:09.324+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:03:09.330+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:03:09.330+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:03:09.332+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:09.332+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:03:09.335+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:09.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:03:09.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:03:09.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.029 seconds
[2025-04-04T23:03:39.652+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:03:39.658+0000] {processor.py:186} INFO - Started process (PID=307) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:03:39.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:03:39.660+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:39.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:03:39.663+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:03:39.662+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:03:39.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:03:39.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:04:10.109+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:04:10.115+0000] {processor.py:186} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:04:10.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:04:10.118+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:10.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:04:10.120+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:10.119+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:04:10.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:04:10.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:04:40.512+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:04:40.518+0000] {processor.py:186} INFO - Started process (PID=313) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:04:40.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:04:40.521+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:40.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:04:40.523+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:04:40.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:04:40.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:04:40.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:05:10.910+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:05:10.917+0000] {processor.py:186} INFO - Started process (PID=316) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:05:10.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:05:10.920+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:10.920+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:05:10.923+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:10.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:05:10.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:05:10.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:05:41.329+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:05:41.335+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:05:41.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:05:41.338+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:41.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:05:41.340+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:05:41.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:05:41.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:05:41.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:06:11.630+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:06:11.637+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:06:11.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:06:11.640+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:11.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:06:11.643+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:11.642+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:06:11.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:06:11.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.036 seconds
[2025-04-04T23:06:42.052+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:06:42.059+0000] {processor.py:186} INFO - Started process (PID=325) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:06:42.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:06:42.061+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:42.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:06:42.064+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:06:42.063+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:06:42.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:06:42.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:07:12.488+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:07:12.496+0000] {processor.py:186} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:07:12.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:07:12.498+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:12.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:07:12.501+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:12.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:07:12.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:07:12.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:07:42.878+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:07:42.884+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:07:42.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:07:42.887+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:42.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:07:42.890+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:07:42.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:07:42.891+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:07:42.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:08:13.285+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:08:13.293+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:08:13.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:08:13.296+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:13.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:08:13.299+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:13.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:08:13.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:08:13.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.039 seconds
[2025-04-04T23:08:43.689+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:08:43.695+0000] {processor.py:186} INFO - Started process (PID=337) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:08:43.695+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:08:43.697+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:43.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:08:43.700+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:08:43.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:08:43.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:08:43.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.030 seconds
[2025-04-04T23:09:14.083+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:09:14.089+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:09:14.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:09:14.091+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:14.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:09:14.095+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:14.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:09:14.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:09:14.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:09:44.526+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:09:44.532+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:09:44.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:09:44.535+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:44.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:09:44.537+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:09:44.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:09:44.538+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:09:44.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:10:14.951+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:10:14.958+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:10:14.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:10:14.960+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:14.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:10:14.963+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:14.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:10:14.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:10:14.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:10:45.321+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:10:45.328+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:10:45.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:10:45.331+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:45.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:10:45.333+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:10:45.332+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:10:45.334+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:10:45.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:11:15.682+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:11:15.688+0000] {processor.py:186} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:11:15.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:11:15.691+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:15.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:11:15.693+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:15.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:11:15.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:11:15.710+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:11:46.057+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:11:46.063+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:11:46.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:11:46.066+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:46.066+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:11:46.069+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:11:46.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:11:46.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:11:46.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:12:16.396+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:12:16.401+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:12:16.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:12:16.404+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:16.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:12:16.407+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:16.406+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:12:16.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:12:16.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.030 seconds
[2025-04-04T23:12:46.706+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:12:46.713+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:12:46.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:12:46.715+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:46.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:12:46.717+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:12:46.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:12:46.718+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:12:46.735+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:13:17.078+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:13:17.084+0000] {processor.py:186} INFO - Started process (PID=364) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:13:17.084+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:13:17.086+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:17.086+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:13:17.089+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:17.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:13:17.089+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:13:17.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.030 seconds
[2025-04-04T23:13:47.439+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:13:47.446+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:13:47.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:13:47.448+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:47.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:13:47.451+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:13:47.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:13:47.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:13:47.470+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:14:17.803+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:14:17.809+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:14:17.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:14:17.811+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:17.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:14:17.814+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:17.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:14:17.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:14:17.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:14:48.184+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:14:48.190+0000] {processor.py:186} INFO - Started process (PID=373) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:14:48.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:14:48.193+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:48.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:14:48.195+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:14:48.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:14:48.196+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:14:48.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:15:18.479+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:15:18.486+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:15:18.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:15:18.489+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:18.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:15:18.491+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:18.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:15:18.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:15:18.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.030 seconds
[2025-04-04T23:15:48.829+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:15:48.836+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:15:48.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:15:48.838+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:48.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:15:48.841+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:15:48.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:15:48.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:15:48.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:16:19.174+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:16:19.179+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:16:19.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:16:19.182+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:19.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:16:19.184+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:19.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:16:19.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:16:19.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:16:49.517+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:16:49.524+0000] {processor.py:186} INFO - Started process (PID=385) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:16:49.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:16:49.526+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:49.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:16:49.529+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:16:49.528+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:16:49.529+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:16:49.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:17:19.899+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:17:19.906+0000] {processor.py:186} INFO - Started process (PID=388) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:17:19.906+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:17:19.908+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:17:19.908+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:17:19.911+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:17:19.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:17:19.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:17:19.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:17:50.232+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:17:50.237+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:17:50.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:17:50.239+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:17:50.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:17:50.241+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:17:50.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:17:50.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:17:50.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.029 seconds
[2025-04-04T23:18:20.591+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:18:20.597+0000] {processor.py:186} INFO - Started process (PID=394) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:18:20.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:18:20.599+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:20.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:18:20.602+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:20.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:18:20.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:18:20.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:18:50.912+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:18:50.917+0000] {processor.py:186} INFO - Started process (PID=397) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:18:50.917+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:18:50.919+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:50.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:18:50.921+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:18:50.921+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:18:50.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:18:50.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:19:21.286+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:19:21.292+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:19:21.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:19:21.294+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:21.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:19:21.298+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:21.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:19:21.298+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:19:21.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.036 seconds
[2025-04-04T23:19:51.627+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:19:51.631+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:19:51.632+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:19:51.633+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:51.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:19:51.636+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:19:51.635+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:19:51.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:19:51.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.028 seconds
[2025-04-04T23:20:21.951+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:20:21.957+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:20:21.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:20:21.959+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:21.959+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:20:21.962+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:21.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:20:21.962+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:20:21.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:20:52.286+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:20:52.292+0000] {processor.py:186} INFO - Started process (PID=409) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:20:52.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:20:52.294+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:52.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:20:52.298+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:20:52.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:20:52.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:20:52.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:21:22.607+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:21:22.613+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:21:22.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:21:22.616+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:22.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:21:22.619+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:22.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:21:22.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:21:22.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:21:52.977+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:21:52.982+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:21:52.983+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:21:52.985+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:52.984+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:21:52.988+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:21:52.986+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:21:52.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:21:53.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:22:23.342+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:22:23.348+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:22:23.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:22:23.351+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:23.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:22:23.354+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:23.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:22:23.354+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:22:23.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:22:53.672+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:22:53.677+0000] {processor.py:186} INFO - Started process (PID=421) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:22:53.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:22:53.680+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:53.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:22:53.683+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:22:53.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:22:53.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:22:53.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:23:24.004+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:23:24.009+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:23:24.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:23:24.012+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:24.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:23:24.015+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:24.014+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:23:24.016+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:23:24.033+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:23:54.342+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:23:54.349+0000] {processor.py:186} INFO - Started process (PID=427) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:23:54.349+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:23:54.351+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:54.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:23:54.353+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:23:54.352+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:23:54.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:23:54.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.030 seconds
[2025-04-04T23:24:24.686+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:24:24.692+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:24:24.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:24:24.695+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:24.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:24:24.697+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:24.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:24:24.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:24:24.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:24:54.958+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:24:54.964+0000] {processor.py:186} INFO - Started process (PID=433) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:24:54.964+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:24:54.966+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:54.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:24:54.968+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:24:54.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:24:54.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:24:54.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.029 seconds
[2025-04-04T23:25:25.246+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:25:25.253+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:25:25.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:25:25.255+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:25.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:25:25.258+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:25.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:25:25.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:25:25.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:25:55.548+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:25:55.555+0000] {processor.py:186} INFO - Started process (PID=439) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:25:55.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:25:55.558+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:55.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:25:55.561+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:25:55.560+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:25:55.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:25:55.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:26:25.870+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:26:25.877+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:26:25.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:26:25.880+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:25.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:26:25.882+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:25.882+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:26:25.883+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:26:25.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:26:56.230+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:26:56.236+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:26:56.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:26:56.238+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:56.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:26:56.240+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:26:56.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:26:56.241+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:26:56.258+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:27:26.451+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:27:26.458+0000] {processor.py:186} INFO - Started process (PID=448) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:27:26.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:27:26.461+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:26.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:27:26.464+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:26.463+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:27:26.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:27:26.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:27:56.750+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:27:56.756+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:27:56.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:27:56.759+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:56.759+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:27:56.763+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:27:56.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:27:56.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:27:56.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:28:27.077+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:28:27.082+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:28:27.083+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:28:27.085+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:27.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:28:27.088+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:27.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:28:27.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:28:27.105+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:28:57.373+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:28:57.379+0000] {processor.py:186} INFO - Started process (PID=457) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:28:57.379+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:28:57.381+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:57.380+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:28:57.383+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:28:57.382+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:28:57.384+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:28:57.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:29:27.659+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:29:27.667+0000] {processor.py:186} INFO - Started process (PID=460) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:29:27.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:29:27.669+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:27.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:29:27.673+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:27.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:29:27.673+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:29:27.692+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.036 seconds
[2025-04-04T23:29:57.894+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:29:57.900+0000] {processor.py:186} INFO - Started process (PID=463) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:29:57.900+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:29:57.902+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:57.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:29:57.905+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:29:57.904+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:29:57.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:29:57.921+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.029 seconds
[2025-04-04T23:30:28.163+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:30:28.170+0000] {processor.py:186} INFO - Started process (PID=466) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:30:28.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:30:28.172+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:28.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:30:28.176+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:28.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:30:28.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:30:28.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.035 seconds
[2025-04-04T23:30:58.458+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:30:58.466+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:30:58.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:30:58.468+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:58.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:30:58.471+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:30:58.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:30:58.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:30:58.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:31:28.704+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:31:28.709+0000] {processor.py:186} INFO - Started process (PID=472) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:31:28.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:31:28.711+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:28.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:31:28.714+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:28.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:31:28.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:31:28.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.030 seconds
[2025-04-04T23:31:58.984+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:31:58.990+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:31:58.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:31:58.993+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:58.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:31:58.997+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:31:58.996+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:31:58.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:31:59.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:32:29.205+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:32:29.212+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:32:29.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:32:29.214+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:29.214+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:32:29.217+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:29.216+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:32:29.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:32:29.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:32:59.477+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:32:59.484+0000] {processor.py:186} INFO - Started process (PID=481) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:32:59.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:32:59.487+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:59.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:32:59.489+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:32:59.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:32:59.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:32:59.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:33:29.762+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:33:29.769+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:33:29.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:33:29.771+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:33:29.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:33:29.774+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:33:29.773+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:33:29.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:33:29.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:34:00.016+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:34:00.026+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:34:00.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:34:00.029+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:00.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:34:00.033+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:00.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:34:00.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:34:00.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.039 seconds
[2025-04-04T23:34:30.183+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:34:30.188+0000] {processor.py:186} INFO - Started process (PID=490) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:34:30.189+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:34:30.191+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:30.190+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:34:30.193+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:34:30.192+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:34:30.194+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:34:30.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:35:00.466+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:35:00.473+0000] {processor.py:186} INFO - Started process (PID=493) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:35:00.474+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:35:00.477+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:00.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:35:00.479+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:00.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:35:00.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:35:00.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.039 seconds
[2025-04-04T23:35:30.733+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:35:30.739+0000] {processor.py:186} INFO - Started process (PID=496) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:35:30.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:35:30.742+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:30.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:35:30.746+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:35:30.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:35:30.746+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:35:30.763+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:36:01.014+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:36:01.020+0000] {processor.py:186} INFO - Started process (PID=499) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:36:01.020+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:36:01.022+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:01.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:36:01.025+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:01.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:36:01.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:36:01.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.031 seconds
[2025-04-04T23:36:31.263+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:36:31.270+0000] {processor.py:186} INFO - Started process (PID=502) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:36:31.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:36:31.273+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:31.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:36:31.275+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:36:31.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:36:31.276+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:36:31.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.040 seconds
[2025-04-04T23:37:01.494+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:37:01.501+0000] {processor.py:186} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:37:01.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:37:01.503+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:01.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:37:01.506+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:01.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:37:01.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:37:01.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:37:31.730+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:37:31.738+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:37:31.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:37:31.741+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:31.741+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:37:31.744+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:37:31.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:37:31.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:37:31.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.037 seconds
[2025-04-04T23:38:02.018+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:38:02.025+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:38:02.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:38:02.028+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:02.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:38:02.030+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:02.029+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:38:02.031+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:38:02.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:38:32.197+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:38:32.204+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:38:32.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:38:32.206+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:32.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:38:32.209+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:38:32.208+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:38:32.209+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:38:32.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:39:02.437+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:39:02.445+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:39:02.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:39:02.447+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:02.447+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:39:02.450+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:02.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:39:02.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:39:02.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.032 seconds
[2025-04-04T23:39:33.113+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:39:33.119+0000] {processor.py:186} INFO - Started process (PID=520) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:39:33.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:39:33.121+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:33.121+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:39:33.124+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:39:33.123+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:39:33.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:39:33.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.029 seconds
[2025-04-04T23:40:03.931+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:40:03.937+0000] {processor.py:186} INFO - Started process (PID=523) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:40:03.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:40:03.939+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:03.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:40:03.942+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:03.941+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:40:03.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:40:03.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:40:34.153+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:40:34.159+0000] {processor.py:186} INFO - Started process (PID=526) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:40:34.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:40:34.162+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:34.161+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:40:34.164+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:40:34.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:40:34.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:40:34.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:41:04.339+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:41:04.347+0000] {processor.py:186} INFO - Started process (PID=529) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:41:04.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:41:04.349+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:04.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:41:04.352+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:04.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:41:04.352+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:41:04.370+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.033 seconds
[2025-04-04T23:41:34.576+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:41:34.581+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:41:34.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:41:34.584+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:34.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:41:34.587+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:41:34.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:41:34.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:41:34.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.034 seconds
[2025-04-04T23:42:04.816+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T23:42:04.824+0000] {processor.py:186} INFO - Started process (PID=535) to work on /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:42:04.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ingestao_weather.py for tasks to queue
[2025-04-04T23:42:04.829+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:42:04.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:42:04.832+0000] {logging_mixin.py:190} INFO - [2025-04-04T23:42:04.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ingestao_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ingestao_weather.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
[2025-04-04T23:42:04.833+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ingestao_weather.py
[2025-04-04T23:42:04.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ingestao_weather.py took 0.039 seconds
